---
# line-length
MD013: false
# no-inline-html
MD033: false
# single-title
MD025:
    # Ignore front matter 'title' property, it is not used in generated markup
    front_matter_title: ""
# no-trailing-punctuation
MD026:
    # Allow headings to end with '?'
    punctuation: ".,;:!"
