site_name: Jellyfin Documentation
theme: readthedocs
markdown_extensions:
  - toc:
      permalink: yes
pages:
  - Home: 'index.md'
  - About: 'about.md'
  - FAQ: 'faq.md'
  - Users:
    - Getting help: 'user-docs/getting-help.md'
    - Client apps: 'user-docs/apps.md'
  - Administrators:
    - Installing Jellyfin: 'administrator-docs/installing.md'
    - Building from Source: 'administrator-docs/building.md'
    - Quick Start: 'administrator-docs/quick-start.md'
    - Migrating from Emby: 'administrator-docs/migrate-from-emby.md'
    - Connectivity: 'administrator-docs/connectivity.md'
    - Plugins: 'administrator-docs/plugins.md'
    - Reverse Proxy: 'administrator-docs/reverse-proxy.md'
    - Users: 'administrator-docs/users.md'
  - Contributors:
    - Contributing: 'contributor-docs/contributing.md'
    - GitHub Issues: 'contributor-docs/issues.md'
    - Development Procedure: 'contributor-docs/contributing-code.md'
    - Branding: 'contributor-docs/branding-guide.md'
    - Release Procedure: 'contributor-docs/release-procedure.md'
  - Developers:
    - Style Guidelines: 'developer-docs/coding-style.md'
extra_css:
  - static/overrides.css
