site_name: Jellyfin Documentation
theme: readthedocs
markdown_extensions:
  - toc:
      permalink: yes
pages:
  - Home: 'index.md'
  - About: 'about.md'
  - FAQ: 'faq.md'
  - Clients: 'clients.md'
  - Getting Help: 'getting-help.md'
  - Administrators:
    - Installing Jellyfin: 'administrator-docs/installing.md'
    - Building from Source: 'administrator-docs/building.md'
    - Quick Start: 'administrator-docs/quick-start.md'
    - Migrating from Emby: 'administrator-docs/migrate-from-emby.md'
    - Plugins: 'administrator-docs/plugins.md'
    - Port Bindings: 'administrator-docs/port-bindings.md'
    - Connectivity: 'administrator-docs/connectivity.md'
    - Reverse Proxy: 'administrator-docs/reverse-proxy.md'
    - Hardware Acceleration: 'administrator-docs/hardware-acceleration.md'
  - Contributors:
    - Contributing: 'contributor-docs/contributing.md'
    - GitHub Issues: 'contributor-docs/issues.md'
    - Development: 'contributor-docs/contributing-code.md'
    - Branding: 'contributor-docs/branding-guide.md'
    - Release Procedure: 'contributor-docs/release-procedure.md'
  - Media:
    - Movies: 'media/movies.md'
    - Music: 'media/music.md'
    - Shows: 'media/shows.md'
    - Subtitles: 'media/subtitles.md'
  - Server:
    - Devices: 'server/devices.md'
    - Libraries: 'server/libraries.md'
    - Live TV: 'server/live-tv.md'
    - Notifications: 'server/notifications.md'
    - Plugins: 'server/plugins.md'
    - Settings: 'server/settings.md'
    - Tasks: 'server/tasks.md'
    - Transcoding: 'server/transcoding.md'
    - Users: 'server/users.md'
  - Plugins:
    - TVHeadend: 'plugins/tvheadend.md'
    - Open Subtitles: 'plugins/open-subtitles.md'
extra_css:
  - static/overrides.css
